language: android
android:
  components:
  - platform-tools
  - build-tools-22.0.1
  - android-22
  - add-on
  - extra
env:
  global:
  - secure: DibPVxMfnDPMGjah1qvsLbM/ttthR9U2AhsVc2FJoT07KuIVkLhxTppf9Xqf87V2uylA6dk/vGJ2PBSy8sMvmc0jd00SNsrCCIVL281uXgyG9Ng0qi1xPMMMnUd816eI8q2SAA4pncQ5QQpQ2s5nzkwfPQYlUqXLOsu9Khm5YxFUdiQOaXXgPcl0bc5kTrW55DGpqKQXqXNX1ZmzuhSpRcjDaytRR+r/S+Yb5kqCLoJBYQOGDV1lZ3BAzAJqaW6XgrV/MncJbCqcfZWP9BOlVhURKHH3E2Oq0DXwDMLQEAb8zKPTIU6zrhuAqguyNPevIRTv73TQaPlzR9AyGZEWoDTGPkq81HvuvpFzUa2JoLZiubu1JwKI8oOAD6+nRjUBAU9+o3zqKIF8zEAirAyZC61dBFqEi+ZjPuh/AANwKW4vgYrEuGW3QnOhy/425Dwa/SnvGhoG26SsS7yCg1vuFuTZBhwlx9j3Y3ENen2sZ8banbh38kWGPjW673Kwf0PCbmyGmN/H+f6Naj0MNknoNt70P9YIwBLUkndV34i1GgIS8UyBO73lAIfwk7FlV5Gw6LCpiFFTq5PU6ASCo9yGeNEW56ih9G10sf0/yjfG/wWy/iIvWIXpYTxsNs3M4l7w4Kzs4Pc/kjGuOxVDEsWzU2eFUzpH8YWdyKCf/qXkJ5M=
  - secure: kziYAX4iuVOaivF8FihRJONmax2qBfXE3xuAOURuXakzcAXTyV2z/ajpjJ2aopMygxmnWOA1B/CSWGJMfLTO2cRIp/gsIRyAVTQCVZ1iagj5rIYo6rgxRZ5wUxErUbauL+a+X+auXEYW6PL+WY6rBKmrXkpn/6bqfXqv1gwxKmg+xRCQE97VyokTrVLYN8IpMZ4EyPJAYpGK4NwaHm8AJ9sJlOED+83PhFX6Ojn1Tiz5RSPlL6dy6ejfQNfXbOvur2aYER+VVnqutuuLP1fQZh9Kuf2N0MwQolxmatpgwUp9KKt62xALz3SwvE0+EgPLkM4m8Oux8ZG3axOedkufB5q9loGjXzAi8rICnHnUTL8UrxZG4Ol8L14VtJnTYafxZa0YWbEzXdI+lOm/ZvboPzvXaDebPGtBJIAKikxgWhPwxJJ0CrfRUsMpaCmglojapD4H9iNh8xW5Av+ukPCsQyp/txmL6jgpTUpzyuZtayV7B0ZY4HMEcrNMiD3fQA31vKSGNh25sq2UCENqZ1ZVGr5ME8wSOmrSUv+NDECH6ehR25GH1T5J3q2hf60SQy6OOANe9ONioSaGdgc3SYpJwQc7wAa5P/616rJOFwcIBUxJfCNnHrceqcnGmxWIjn6fbkQqnKiiHDKtDTk1VkQVxRRAIaxiBB3mvv91Rhn35RM=
  - secure: VbAD4ZR0d2BuJ8rvQ5rNBHiN3GCuc7e7EBsPycq8g68gSyXtEyvfRFC8xfIJL1K7sO/3AcU6BpuL9EdHtEmkDFmtKkKZ83DwB4ec2aQo64lzk67D+J9JSWrSlBP/MiH9vI5N+Ua4aaijFVgoQNii9NTktTMa5hXN1/1dnHWSq0JUvbO7j3JdzxgvtBx3nYDe5A4aNfcpYA50aabZiDMlP8+JLaqSetK4O4W4dkAAxgCxbcunq4tMCoIeyOTmFW40bkrNKd1aXvurMfFxXWu2wG3if/VirCwN+wWhH+QzxCsCqtGquSJ1lk0f87XzLvNv0oPyaJKtOIwvfCMIvk2Wqte+gjHqRyb4uClUlaQTOjw1+WcDJG6f6JgQUpEDLBKkNwFAxG32gVNEz8u5W5CihTTXMGr6VsRKBcBmpvnDeuppd0sDjwZBuHvVv7QrVttp0E4n86EHnFzfmiIB9Wv75sB7RwqkIezTf7STQb6C4KYY9ynKCc1AivGmjMjprTjwkvYtv4xRchtYf1pJAIlM50znY7po14r/7sOTiXb5iNsEY5AT+rqb3hN1Qpi1w0JGXLuZF21O27sKOQaBjwp/HBQ21ON4IUmHiaQXq19s60RGeYsjWnVctHfVQe/41isFX+XvJLq2clsNRLXdKjYFzB0uB6LkAGcKlNxkAmhW+Dw=
install:
  - npm install
  - npm install -g cordova ionic bower
  - bower install
script: 
  - ./ci.sh
notifications:
  email:
    on_success: never